version: "1"

services:
    next-server:
        build: .
        image: nextjs
        container_name: next-server
        ports:
            - "3005:3000"
        volumes:
            - ../images:/app/public/images
        restart: on-failure
