version: "1"

services:
    next-server:
        build: .
        image: nextjs
        container_name: next-server
        ports:
            - "3000:3000"
        volumes:
            - /home/shared/images:/app/public/images
        restart: on-failure
