import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Card from "components/card";
import { getAuth, signOut } from "firebase/auth";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="p-8">
                <div className="flex flex-wrap gap-8 justify-center">
                    {[...Array(30)].map((i) => (
                        <Card key={i} />
                    ))}
                </div>
            </div>
        </div>
    );
};

export default Home;
