import "./globals.css";

import type { Metadata } from "next";

import Header from "@/components/header";

import SessionProviderComponent from "./session-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <SessionProviderComponent>
                    <div className="flex flex-col min-h-full">
                        <Header />
                        <div className="flex grow [&>*]:grow">{children}</div>
                    </div>
                </SessionProviderComponent>
            </body>
        </html>
    );
}
